name: .NET CI Build

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build solution
      - name: Build project
        run: dotnet build --configuration Release --no-restore
